-- Core NLP Engine Configuration (System Data)
INSERT INTO SQL_Action (sql_query, target_module) VALUES
('SELECT * FROM Patient WHERE 1=1 :conditions', 'M15'),
('SELECT * FROM Patient WHERE patient_id = :patient_id', 'M15'),
('SELECT * FROM Visit WHERE patient_id = :patient_id ORDER BY visit_date DESC', 'M15'),
('SELECT COUNT(*) AS total_visits FROM Visit WHERE patient_id = :patient_id', 'M15'),
('SELECT * FROM Visit WHERE patient_id = :patient_id ORDER BY visit_date DESC LIMIT 1', 'M15'),
('SELECT p.name, v.visit_date, v.diagnosis FROM Patient p JOIN Visit v ON p.patient_id = v.patient_id WHERE 1=1 :conditions ORDER BY v.visit_date DESC', 'M15'),
('SELECT b.amount, b.payment_status, v.visit_date, p.name AS patient_name FROM Billing b JOIN Visit v ON b.visit_id = v.visit_id JOIN Patient p ON v.patient_id = p.patient_id WHERE 1=1 :conditions ORDER BY v.visit_date DESC', 'M15'),
('SELECT DISTINCT p.patient_id, p.name, p.age, p.gender, v.diagnosis FROM Patient p JOIN Visit v ON p.patient_id = v.patient_id WHERE LOWER(v.diagnosis) LIKE LOWER(CONCAT(''%'','':diagnosis'',''%'')) AND 1=1 :conditions', 'M15'),
('SELECT pr.medicine_name, pr.dosage, pr.duration, v.visit_date, v.diagnosis FROM Prescription pr JOIN Visit v ON pr.visit_id = v.visit_id WHERE v.patient_id = :patient_id ORDER BY v.visit_date DESC', 'M15'),
('SELECT * FROM Doctor ORDER BY specialization', 'M15'),
('SELECT p.name AS patient_name, v.visit_date, v.diagnosis, d.name AS doctor_name FROM Visit v JOIN Patient p ON v.patient_id = p.patient_id JOIN Doctor d ON v.doctor_id = d.doctor_id WHERE v.doctor_id = :patient_id ORDER BY v.visit_date DESC', 'M15'),
('SELECT p.name, v.visit_date, v.diagnosis, d.name AS doctor FROM Visit v JOIN Patient p ON v.patient_id = p.patient_id JOIN Doctor d ON v.doctor_id = d.doctor_id WHERE DATE(v.visit_date) = CURDATE()', 'M15'),
('SELECT p.name, v.visit_date, v.diagnosis FROM Visit v JOIN Patient p ON v.patient_id = p.patient_id WHERE MONTH(v.visit_date) = MONTH(CURDATE()) AND YEAR(v.visit_date) = YEAR(CURDATE()) ORDER BY v.visit_date DESC', 'M15'),
('SELECT COUNT(*) AS total_patients FROM Patient WHERE 1=1 :conditions', 'M15'),
('SELECT p.name, b.amount, b.payment_status, v.visit_date FROM Billing b JOIN Visit v ON b.visit_id = v.visit_id JOIN Patient p ON v.patient_id = p.patient_id WHERE b.payment_status = ''Pending'' :conditions ORDER BY v.visit_date DESC', 'M15'),
('SELECT t.test_name, r.result_value, t.unit, r.result_date, CASE WHEN r.result_value > t.normal_max THEN ''HIGH'' WHEN r.result_value < t.normal_min THEN ''LOW'' ELSE ''NORMAL'' END as status FROM LabResult r JOIN LabTest t ON r.test_id = t.test_id WHERE r.patient_id = :patient_id ORDER BY r.result_date DESC', 'M14'),
('SELECT t.test_name, r.result_date, r.result_value, (r.result_value - LAG(r.result_value) OVER (PARTITION BY t.test_id ORDER BY r.result_date)) as change_from_last_visit FROM LabResult r JOIN LabTest t ON r.test_id = t.test_id WHERE r.patient_id = :patient_id ORDER BY t.test_name, r.result_date DESC', 'M14'),
('SELECT p.name, v.visit_date, v.diagnosis, d.name AS doctor FROM Visit v JOIN Patient p ON v.patient_id = p.patient_id JOIN Doctor d ON v.doctor_id = d.doctor_id WHERE DATE(v.visit_date) = '':visit_date'' ORDER BY v.visit_date DESC', 'M15');

INSERT INTO CommandTemplate (template_pattern, keyword, command_type, sql_action_id) VALUES
('all patients',         'patients,all,age,female,above,below',       'Retrieval',   1),
('patient by id',        'patient,id,find,number',                    'Retrieval',   2),
('visits of patient',    'visits,visit,list,show',                    'Retrieval',   3),
('count visits',         'count,visits,total,how',                    'Calculation', 4),
('latest visit',         'latest,recent,last,visit',                  'Retrieval',   5),
('patient history',      'history,previous,past,old',                 'Retrieval',   6),
('billing',              'billing,bill,payment,paid',                 'Retrieval',   7),
('diagnosis patients',   'diabetic,diagnosis,disease,patients',       'Retrieval',   8),
('diagnosis filter',     'hypertension,thyroid,fever,asthma',         'Retrieval',   8),
('prescriptions',        'prescription,prescriptions,medicine,drugs', 'Retrieval',   9),
('doctors',              'doctors,doctor,specialist,specialists',     'Retrieval',   10),
('doctor visits',        'doctor,conducted,seen,treated',             'Retrieval',   11),
('today visits',         'today,visits,todays,current',               'Retrieval',   12),
('this month visits',    'month,monthly,this,week',                   'Retrieval',   13),
('count patients',       'count,patients,total,many',                 'Calculation', 14),
('pending bills',        'pending,unpaid,bills,dues',                 'Retrieval',   15),
('patient lab results',  'lab,labs,test,results',                     'Retrieval',   16),
('patient lab trends',   'trend,trends,change,tracking',              'Retrieval',   17),
('specific date visits', 'date,on,visits,day',                        'Retrieval',   18);
